### PR TITLE
Add support for digest using GnuTLS

### PR DESCRIPTION
**Pull request by Jakuje**
the mhash crypto is not updated for 15 years and I was not able to make it working in Fedora nor in Mac CI. Libcrypt usage has also its downsides as it is not always available. My proposal is to implement digests with GnuTLS library.

This also extends the hash tests and CI to run with all of the combinations, as well as the README which still lists mhash as mandatory, which is no longer the case.

### CODE REVIEW

**Comment by hvhaugwitz** [comment]
At first many thanks for your pull request.

AIDE 0.19 will deprecate/remove several outdated/obsolete hash functions like `md5` in favour of newer hash functions like `SHA-3` (see also #150).

The proposed GnuTLS library does not support `SHA-3`; hence unfortunately I cannot merge this pull request.

At the moment I'm working on replacing `libmhash` with `libnettle`; would you be willing to adjust the remaining changes for the CI and the hash tests to the new code base (once it has been pushed)?

**Comment by Jakuje** [comment]
> At first many thanks for your pull request.

Thank you for the reply!

> AIDE 0.19 will deprecate/remove several outdated/obsolete hash functions like `md5` in favour of newer hash functions like `SHA-3` (see also #150).

Good to hear it. Finding some of the old algorithms was quite a pain :)

> The proposed GnuTLS library does not support `SHA-3`; hence unfortunately I cannot merge this pull request.

I had the impression that the SHA3 should be already supported everywhere, but it looks like I was wrong in GnuTLS. I did not see an issue with this as there was no pre-existing support for that in here neither.

> At the moment I'm working on replacing `libmhash` with `libnettle`; would you be willing to adjust the remaining changes for the CI and the hash tests to the new code base (once it has been pushed)?

Sure! Let me know when the changes will be ready. I hope at least the remaining changes will be for some use.

**Comment by radosroka** [comment]
@hvhaugwitz is there any update for libnettle support?

**Comment by Jakuje** [comment]
Rebased on current master. The CI results are visible in my fork: https://github.com/Jakuje/aide/commits/gnutls/

I discussed the SHA3 in GnuTLS with the developers and they say the SHA3 should be indeed supported (as it is using nettle as cryptographic backend, but I did not really test that):
https://www.gnutls.org/manual/gnutls.html#gnutls_005fdigest_005falgorithm_005ft

**Comment by hvhaugwitz** [comment]
> @hvhaugwitz is there any update for libnettle support?
@radosroka it will be part of AIDE v0.19; I plan to upload the change within the next couple of weeks

**Comment by Jakuje** [comment]
Thank you for pulling the relevant test changes (and getting rid of mhash)!

**Pull request closed without merging**
