### PR TITLE
Add Russian GOST crypto algorithms

### PR DESCRIPTION
**Pull request by kostap8**
Sinse 1.7.7-1 verision libgcrypt support russian GOST algorithms. I add it to project and add option --with-gcrypt-gost to enable it, if necessary to enable it.

### CODE REVIEW

**Comment by hvhaugwitz** [comment]
Thanks for your contribution.

Seeing the big amount of code changes needed to simply add some hash algorithms made me reflect about the code structure; so currently I'm refactoring the attribute and hashsum code. Please wait until I pushed my changes. Hashsum addition should be way easier than.

**Comment by kostap8** [comment]
Okey. Please, notify me, when all be done.
I think too, that the patch needs to be updated, cause you added DB_GOSTR3411_94 hash in master.

**Comment by hvhaugwitz** [comment]
> I think too, that the patch needs to be updated, cause you added DB_GOSTR3411_94 hash in master.

DB_GOSTR3411_94 was already present with mhash and I just made it also available with gcrypt.

I tend to merely add the `stribog256` and `stribog512` hashes, as they replace the obsolete hashes defined in the old GOST R 34.11-94 standard.

**Comment by kostap8** [comment]
Okey, great!

**Pull request closed without merging**
